// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPN9RseMugFTjupHE7TNqgxXWB77h0MiI',
    appId: '1:768170962921:web:06e832f55550f5f8ace578',
    messagingSenderId: '768170962921',
    projectId: 'authfluttersimple',
    authDomain: 'authfluttersimple.firebaseapp.com',
    storageBucket: 'authfluttersimple.firebasestorage.app',
    measurementId: 'G-MEWMZ9S75F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYeybMqUSV07nnQ2OnYJxI-j47wiN4538',
    appId: '1:768170962921:android:feff16e3d69797e5ace578',
    messagingSenderId: '768170962921',
    projectId: 'authfluttersimple',
    storageBucket: 'authfluttersimple.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiSZC42WbH7OEUadPEjWeT4cUngCXL-kc',
    appId: '1:768170962921:ios:4eaf34e57f7a9c76ace578',
    messagingSenderId: '768170962921',
    projectId: 'authfluttersimple',
    storageBucket: 'authfluttersimple.firebasestorage.app',
    iosBundleId: 'com.example.authAppSimple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiSZC42WbH7OEUadPEjWeT4cUngCXL-kc',
    appId: '1:768170962921:ios:4eaf34e57f7a9c76ace578',
    messagingSenderId: '768170962921',
    projectId: 'authfluttersimple',
    storageBucket: 'authfluttersimple.firebasestorage.app',
    iosBundleId: 'com.example.authAppSimple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPN9RseMugFTjupHE7TNqgxXWB77h0MiI',
    appId: '1:768170962921:web:97e39601103fc3b9ace578',
    messagingSenderId: '768170962921',
    projectId: 'authfluttersimple',
    authDomain: 'authfluttersimple.firebaseapp.com',
    storageBucket: 'authfluttersimple.firebasestorage.app',
    measurementId: 'G-EB9WC552PZ',
  );

}